# Generated by Django 5.1 on 2024-08-15 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_portion_cost_recipe_portions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='method',
            old_name='Recipe',
            new_name='recipe',
        ),
    ]
