# Generated by Django 5.1 on 2024-08-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_recipe_method_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='Steps',
        ),
        migrations.AddField(
            model_name='method',
            name='steps',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
