# Generated by Django 5.1 on 2024-08-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_method_steps_method_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='steps',
            field=models.TextField(null=True),
        ),
    ]
