# Generated by Django 5.1 on 2024-08-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_ingredients_quantity_alter_recipe_portions'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('ml', 'ml'), ('', '')], default='', max_length=50),
        ),
    ]
