# Generated by Django 5.1 on 2024-08-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_ingredients_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('ml', 'ml'), ('', '')], default='', max_length=50, null=True),
        ),
    ]
