# Generated by Django 5.1 on 2024-08-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('product_type', models.CharField(choices=[('Dairy', 'Dairy'), ('Meat', 'Meat'), ('Fish', 'Fish'), ('Shell Fish', 'Shell Fish'), ('Dried', 'Dried'), ('Vegetable', 'Vegetable'), ('Fruit', 'Fruit'), ('Herbs/Spices', 'Herbs/Spices'), ('Sauces', 'Sauces'), ('Oils', 'Oils'), ('Rice', 'Rice'), ('Baking', 'Baking'), ('Confectionery', 'Confectionery'), ('Drinks', 'Drinks'), ('Other', 'Other')], default='Dairy', max_length=50)),
                ('product_cost', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('product_weight', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('product_quantity', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
    ]
