# Generated by Django 5.1 on 2024-08-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_subcategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_weight',
            new_name='weight',
        ),
    ]
