# Generated by Django 5.1 on 2024-08-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='liquid_vol',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, null=True),
        ),
    ]
